### ISSUE TITLE
Fix composer.json in order to render Extension at docs.typo3.org

### ISSUE THREAD

**Issue by DanielSiepmann** [joachimruhs/myleaflet#1]
Hey,

in order to allow the extension to be rendered at docs.typo3.org, the `composer.json` file has to be adjusted. Right now the extension key `ext_key` is configured. This has to be replaced with the real extension key, which looks like `myleaflet`.

Otherwise we can not approve the extension.

Once fixed, please close this Issue, so we can remove the extension from our rendering blacklist.
You can also contact us within typo3.slack.com `#typo3-documentation`.

**Comment by joachimruhs** [comment]
Hello,

I fixed composer.json and in intercept.typo3.com I see the message

25.11.19, 10:32 
Can not render documentation: The repository at https://github.com/joachimruhs/myleaflet.git due to it being blacklisted. 

What else is wrong, what can I do?

Regards

    Joachim Ruhs


From: Daniel Siepmann 
Sent: Monday, November 25, 2019 9:56 AM
To: joachimruhs/myleaflet 
Cc: Subscribed 
Subject: [joachimruhs/myleaflet] Fix composer.json in order to render Extension at docs.typo3.org (#1)

Hey,

in order to allow the extension to be rendered at docs.typo3.org, the composer.json file has to be adjusted. Right now the extension key ext_key is configured. This has to be replaced with the real extension key, which looks like myleaflet.

Otherwise we can not approve the extension.

**Comment by joachimruhs** [comment]
Done

**Comment by DanielSiepmann** [comment]
Thanks for fast response.

Your extension is now accepted and already rendered: https://docs.typo3.org/p/WSR/myleaflet/master/en-us/
